# Generated by Django 5.1.6 on 2025-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0005_remove_teammember_permissions_remove_teammember_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='roles',
            field=models.ManyToManyField(related_name='team_members', to='Authentication.role'),
        ),
    ]
